

- id: 10.1016/j.nicl.2022.103139
  image: https://meghanvdmeer.github.io/M.I.N.DLab/images/journal_covers/Elsevier_logo.png
  extra-links:
    - type: pdf
      link: pdfs/2022_Alvand_etal_Elsevier.pdf
  tags:
    - APD
    - fMRI
    - Network Neuroscience
    - Pediatric





- id: 10.1371/journal.pone.0262563
  image: https://meghanvdmeer.github.io/M.I.N.DLab/images/journal_covers/plosone.png
  extra-links:
    - type: pdf
      link: pdfs/2022_Virues-Ortega_etal_PlosOne.pdf
  tags:
    - ASD
    - DTI
